#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER




#define TAU_PWM_EXAMPLE_MSEC_PER_SEC           (1000)
#define TAU_PWM_EXAMPLE_DESIRED_PERIOD_MSEC    (20)


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    fsp_err_t err = FSP_SUCCESS;
    /* Initializes the module. */
    err = R_TAU_PWM_Open(&g_timer0_ctrl, &g_timer0_cfg);
    /* Handle any errors. This function should be defined by the user. */
    assert(FSP_SUCCESS == err);

    /* Start the timer. */
    (void) R_TAU_PWM_Start(&g_timer0_ctrl);


    /* Get the source clock frequency (in Hz) */
     timer_info_t info;
     (void) R_TAU_PWM_InfoGet(&g_timer0_ctrl, &info);
     uint32_t timer_freq_hz = info.clock_frequency;

     /* Set the calculated period. This will return an error if parameter checking is enabled and the calculated
      * period is larger than UINT16_MAX. */
     err = R_TAU_PWM_PeriodSet(&g_timer0_ctrl, 80000);
     assert(FSP_SUCCESS == err);


     /* Get the current period setting. */
     (void) R_TAU_PWM_InfoGet(&g_timer0_ctrl, &info);
     uint32_t current_period_counts = info.period_counts;

     /* Set the calculated duty cycle. */
     err = R_TAU_PWM_DutyCycleSet(&g_timer0_ctrl, 2000, 3);
     assert(FSP_SUCCESS == err);

     /* Set the calculated duty cycle. */
     err = R_TAU_PWM_DutyCycleSet(&g_timer0_ctrl, 6000, 5);
     assert(FSP_SUCCESS == err);





#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
